Repository PupTrainer/fe_puptrainer, pull requests merged in 2022-07, with the labels that each got.

#2 Setup/homepage
  cypress.config.js
  cypress/e2e/spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/About.js
  src/App.js
  src/Form.js
  src/Homepage.js
  src/Info.js
  src/Login.js
  src/Nav.css
  src/Nav.js
  src/index.js
Labels: FE

#6 Implment router to render specific components
  src/App.js
Labels: enhancement

#20 Add Sass to project
  package-lock.json
  package.json
Labels: documentation

#21 Create 404 page and basic styling
  src/NoPageFound.css
  src/NoPageFound.css.map
  src/NoPageFound.js
  src/NoPageFound.scss
Labels: enhancement

#22 Styling/nav
  .sass-cache/4d0e15994987dfe52df86b09d0a8b352ca3ac80b/nav.sassc
  src/Nav.css
  src/Nav.js
  src/Nav.sass
  src/images/PupTrainerLogo.png
  src/nav.css.map
Labels: enhancement, FE

#24 Add basic login page styling
  src/App.js
  src/Login.js
  src/login.css
  src/login.css.map
  src/login.scss
Labels: enhancement, FE

#26 Feature/login functionality
  src/App.js
  src/Homepage.js
  src/Info.js
  src/Login.js
  src/index.js
Labels: enhancement, FE

#28 Feature/dog profile
  src/App.js
  src/DogProfile.css
  src/DogProfile.css.map
  src/DogProfile.js
  src/DogProfile.scss
  src/Form.js
  src/Homepage.js
  src/Info.js
  src/Login.js
  src/Nav.css
  src/Nav.js
  src/NoPageFound.js
  src/nav.css.map
Labels: enhancement, FE

#34 Add testing for the about page
  cypress/e2e/about-flow.cy.js
Labels: documentation, enhancement, FE

#37 Add skills styling
  src/Skill.css
  src/Skill.css.map
  src/Skill.js
  src/Skill.scss
Labels: enhancement, FE

#38 Test homepage
  cypress/e2e/about-flow.cy.js
  cypress/e2e/homepage-flow.cy.js
  cypress/e2e/login-flow.cy.js
Labels: FE

#40 Feature/known skills
  cypress/e2e/homepage-flow.cy.js
  src/App.js
  src/DogProfile.js
  src/Homepage.js
  src/Info.js
  src/Skill.js
Labels: enhancement, FE

#42 Setup/error handling
  src/App.js
  src/CreateUser.js
  src/Form.js
  src/Homepage.js
  src/Login.js
  src/NoPageFound.js
Labels: enhancement, FE

#43 Fix bug where dog skill wasnt loading
  src/App.js
  src/Form.js
Labels: FE

#45 Feature/styling
  cypress/e2e/homepage-flow.cy.js
  cypress/e2e/login-flow.cy.js
  cypress/e2e/skill-flow.cy.js
  src/About.css
  src/About.css.map
  src/About.js
  src/About.scss
  src/App.css
  src/App.css.map
  src/App.js
  src/App.scss
  src/DogProfile.css
  src/DogProfile.css.map
  src/DogProfile.js
  src/DogProfile.scss
  src/Form.css
  src/Form.css.map
  src/Form.js
  src/Form.scss
  src/Homepage.css
  src/Homepage.css.map
  src/Homepage.scss
  src/Info.css
  src/Info.css.map
  src/Info.js
  src/Info.scss
  src/Nav.css
  src/Skill.css
  src/Skill.css.map
  src/Skill.js
  src/Skill.scss
  src/images/dog.png
Labels: FE

#44 Sad test/login
  cypress/e2e/homepage-flow.cy.js
  cypress/e2e/login-flow.cy.js
Labels: enhancement
